In [1]:
import numpy as np
from IPython.display import display

In [19]:
num25= np.arange(0, 25)
num25.reshape(5, 5)  # same size

display(num25)

# resize: do not return value, allow different size , adds 0
num25.resize(5, 10) # can change size
display(num25)

num25.resize(2, 2) # can change size
display(num25)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

array([[0, 1],
       [2, 3]])

In [45]:
np.random.seed(9)

rand_array = np.random.randint(0, 101, (5, 2))
print(rand_array)
print(' ', np.arange(0, 10))
print('max', rand_array.max())  # max
print('min', rand_array.min())  # min
print('argmax', rand_array.argmax())
print('argmin', rand_array.argmin())
print('shape', rand_array.shape)  # shape of the array

[[92 54]
 [56 22]
 [65 22]
 [52 59]
 [40 91]]
  [0 1 2 3 4 5 6 7 8 9]
max 92
min 22
argmax 0
argmin 3
shape (5, 2)


In [48]:
np.random.seed(9)
rand_array = np.random.randint(0, 10, 10)
print(rand_array)
print(np.arange(0, 10), ' index \n')
print('rand_array[:7]  ', rand_array[:7])
print('rand_array[:7:3]', rand_array[:7:3])
print('rand_array[::-1]', rand_array[::-1])
print('rand_array[-1]  ', rand_array[-1])

[5 6 8 6 1 6 4 8 1 8]
[0 1 2 3 4 5 6 7 8 9]  index 

rand_array[:7]   [5 6 8 6 1 6 4]
rand_array[:7:3] [5 6 4]
rand_array[::-1] [8 1 8 4 6 1 6 8 6 5]
rand_array[-1]   8


In [49]:
arr = np.random.randint(0, 10, (3, 5))
print(arr, '\n')
print('arr[2][4]', arr[2][4])
# print('arr[10]', arr[10])  # Error there is no line 10
print('arr[0]', arr[0])
print('arr[0][::-1]', arr[0][::-1])

[[5 1 0 8 8]
 [8 2 6 8 1]
 [8 3 5 3 6]] 

arr[2][4] 6
arr[0] [5 1 0 8 8]
arr[0][::-1] [8 8 0 1 5]


In [55]:
orig = np.arange(0, 25)
display(orig)
orig[0:10] = 0
display(orig)
# put into 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
orig = np.arange(0, 25)  # input data
display('orig', orig)

copy_orig = orig.copy()
copy_orig[0:10] = 0
display('copy', copy_orig)

display('orig', orig)

'orig'

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

'copy'

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

'orig'

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
orig = np.arange(0, 9)  # input data
display('orig', orig)
display('orig > 5', orig > 5)
display('orig > 5', orig[orig > 5])
display('orig > 5', orig[[False,False,False,False,False,False,True,True,True]])

# Bonus -->
display('orig > 5', orig[[ *([False] * 6), True,  True,  True]])

# [1, 2, 3]
# print(*[1, 2, 3])  # 1, 2, 3  [ *([1,2,3]), 4, 5, 6 ] => [1, 2, 3, 4, 5, 6]

# & and 
# | or 
# ~ not
display('orig > 5 and orig < 9', orig[(orig > 5) & (orig < 9)])
display('orig < 4 or orig >7', orig[(orig < 4) | (orig > 7)])
display('not orig > 5 ', orig[~(orig > 5)])


'orig'

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

'orig > 5'

array([False, False, False, False, False, False,  True,  True,  True])

'orig > 5'

array([6, 7, 8])

'orig > 5'

array([6, 7, 8])

'orig > 5'

array([6, 7, 8])

'orig > 5 and orig < 9'

array([6, 7, 8])

'orig < 4 or orig >7'

array([0, 1, 2, 3, 8])

'not orig > 5 '

8

In [101]:

nums = np.arange(0, 20)
np.save('twenty.npy', nums)

nums = np.load('twenty.npy')

print(nums[(nums > 4) & (nums < 20)])
print(nums[(nums % 5 == 0) | (nums % 7 == 0)])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5  7 10 14 15]


In [114]:
nums = np.arange(0, 9)
display(nums)
print()
display('nums + 2', nums + 2)
display('nums * 2', nums * 2)
display('nums % 2', nums % 2)
display('orig', nums)

nums2 = np.arange(10, 19)  
display(nums2)
nums + nums2  # must be same size


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

'nums + 2'

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

'nums * 2'

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

'nums % 2'

array([0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

'orig'

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

array([10, 12, 14, 16, 18, 20, 22, 24, 26])